[tool.poetry]
name = "goit-ds-hw-02"
version = "0.1.0"
description = "Task management system with SQLite"
authors = ["Serhii Kalynychenko <kalinasergey911@gmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
faker = ">=40.36.0,<41.0.0"
tabulate = ">=0.10.0,<0.11.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
